version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      # local development
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic
    volumes:
      - ./data:/data:/usr/share/elasticsearch/data
networks:
  elastic:
